// Ajustes revisados a mao sobre as regras gerais de src/shared/magias-efeitos.ts.
// anim: [tipo, elemento, forma?, quantidade?]. Condicao "x:1" = dura 1 rodada.
import type { Ajuste } from '../magias-efeitos.ts';

export const AJUSTES: Record<string, Ajuste> = {
  // ---------------- 1º circulo ----------------
  'abencoar-alimentos': { alvo: 'aliado', persistente: undefined, anim: ['cura', 'ouro', 'alimento'], nota: 'Alimento abençoado: +5 PV temporários ou +1 PM temporário ao comer.' },
  'acalmar-animal': { falhou: ['enfeiticado'], anim: ['mental', 'natureza', 'calma'] },
  'acoite-flamejante': {
    alvo: 'inimigo', maxAlvos: 1, falhou: ['em-chamas', 'enredado'], anim: ['arma', 'fogo', 'chicote'],
    usos: [{ nome: 'Chicotear (ação padrão)', alvo: 'inimigo', maxAlvos: 1, dano: '2d6', tipoDano: 'fogo', res: 'ref', sucesso: 'metade', falhou: ['em-chamas', 'enredado'], anim: ['arma', 'fogo', 'chicote'] }],
  },
  'adaga-mental': { falhou: ['atordoado:1'], anim: ['projetil', 'psiquico', 'adaga'] },
  alarme: { alvo: 'nenhum', anim: ['campo', 'arcano', 'runas'] },
  amedrontar: { falhou: ['apavorado:1'], passou: ['abalado:3'], anim: ['mental', 'trevas', 'caveira'], nota: 'Depois de 1 rodada apavorado, o alvo fica abalado.' },
  'area-escorregadia': { falhou: ['caido'], anim: ['campo', 'arcano', 'oleo'] },
  'arma-de-jade': { alvo: 'aliado', maxAlvos: 1, anim: ['arma', 'natureza', 'jade'] },
  'arma-espiritual': { alvo: 'si', dano: undefined, tipoDano: undefined, anim: ['arma', 'ouro', 'espiritual'], nota: 'Reação: quando sofrer ataque corpo a corpo, a arma causa 2d6 no atacante.' },
  'arma-magica': { alvo: 'aliado', maxAlvos: 1, anim: ['arma', 'arcano', 'brilho'] },
  'armadura-elemental': { anim: ['aura', 'eletricidade', 'faiscas'], nota: 'Quem acertar você corpo a corpo sofre 2d6 do tipo escolhido.' },
  'armamento-da-natureza': { alvo: 'aliado', maxAlvos: 1, anim: ['arma', 'natureza', 'galhos'] },
  'arsenal-de-allihanna': { anim: ['arma', 'natureza', 'madeira'] },
  'assobio-perigoso': { alvo: 'nenhum', anim: ['convocacao', 'caos', 'bando'], nota: 'O mestre prepara criaturas de ND igual ao seu nível; atacam qualquer um por perto.' },
  aviso: { persistente: undefined, anim: ['adivinhacao', 'ouro', 'mensagem'] },
  bencao: { anim: ['aura', 'ouro', 'bencao'] },
  'bofetada-de-nimb': { falhou: ['desprevenido:1', 'vulneravel'], passou: ['vulneravel:1'], anim: ['projetil', 'caos', 'mao'] },
  'caminhos-da-natureza': { anim: ['aura', 'natureza', 'folhas'] },
  comando: { falhou: [], anim: ['palavra', 'psiquico', 'ordem'], nota: 'Escolha a ordem: Fuja, Largue, Pare ou Venha (o alvo obedece no turno dele).' },
  compreensao: { alvo: 'qualquer', res: undefined, sucesso: undefined, anim: ['adivinhacao', 'ouro', 'olho'] },
  'concentracao-de-combate': { anim: ['adivinhacao', 'ouro', 'foco'] },
  'conjurar-monstro': {
    alvo: 'nenhum', dano: undefined, tipoDano: undefined, anim: ['convocacao', 'arcano', 'monstro'],
    usos: [{ nome: 'Monstro ataca (ação padrão)', alvo: 'inimigo', maxAlvos: 1, dano: '2d4+2', tipoDano: 'impacto', anim: ['toque', 'arcano', 'garra'] }],
  },
  consagrar: { alvo: 'nenhum', anim: ['campo', 'ouro', 'consagrar'] },
  'controlar-plantas': { anim: ['chao', 'natureza', 'vinhas'] },
  'criar-elementos': { alvo: 'nenhum', dano: undefined, tipoDano: undefined, falhou: undefined, anim: ['convocacao', 'natureza', 'elementos'] },
  'criar-ilusao': { alvo: 'nenhum', res: undefined, sucesso: undefined, anim: ['ilusao', 'caos', 'miragem'] },
  'curar-ferimentos': { anim: ['cura', 'luz', 'maos'] },
  'dardo-gelido': { falhou: ['lento:1'], anim: ['projetil', 'frio', 'dardo'] },
  'descobrir-fraqueza': { falhou: undefined, anim: ['adivinhacao', 'ouro', 'analise'], nota: 'Faça Misticismo +10 para identificar a criatura.' },
  despedacar: { falhou: ['atordoado:1'], anim: ['onda', 'som', 'grito'] },
  'detectar-ameacas': { alvo: 'si', anim: ['adivinhacao', 'ouro', 'radar'] },
  discricao: { alvo: 'si', res: undefined, sucesso: undefined, anim: ['ilusao', 'trevas', 'nevoa'] },
  'disfarce-ilusorio': { res: undefined, sucesso: undefined, anim: ['ilusao', 'caos', 'mascara'] },
  'distracao-fugaz': { falhou: ['desprevenido:1'], anim: ['ilusao', 'caos', 'miragem'] },
  enfeiticar: { anim: ['mental', 'psiquico', 'coracao'] },
  'escapatoria-de-hyninn': { anim: ['aura', 'ar', 'esquiva'] },
  'escudo-da-fe': { persistente: 'rodadas', anim: ['escudo', 'ouro', 'escudo'] },
  escuridao: { alvo: 'nenhum', res: undefined, sucesso: undefined, anim: ['campo', 'trevas', 'escuridao'] },
  'espirito-balistico': {
    alvo: 'nenhum', dano: undefined, tipoDano: undefined, anim: ['convocacao', 'arcano', 'espirito'],
    usos: [{ nome: 'Disparo (início do seu turno)', alvo: 'inimigo', maxAlvos: 1, dano: '1d6+1', tipoDano: 'perfuracao', anim: ['projetil', 'arcano', 'seta'] }],
  },
  'euforia-de-valkaria': { anim: ['aura', 'ouro', 'chamas-coragem'] },
  'execucao-de-thwor': { anim: ['mental', 'sangue', 'marca'], nota: 'Seu próximo ataque contra o alvo, se acertar, vira crítico.' },
  'explosao-de-chamas': { anim: ['cone', 'fogo', 'leque'] },
  'farejar-fortuna': { persistente: undefined, anim: ['adivinhacao', 'ouro', 'moedas'] },
  'flecha-de-luz': { falhou: ['ofuscado:1'], anim: ['projetil', 'luz', 'flecha'] },
  'frescor-de-lena': { alvo: 'aliados', anim: ['onda', 'agua', 'brisa'] },
  'furia-dos-antepassados': { dano2: '1d6', tipoDano2: 'luz', falhou: ['pasmo:1'], anim: ['mental', 'espirito', 'ancestral'] },
  'futuro-melhor': { anim: ['adivinhacao', 'tempo', 'relogio'] },
  hipnotismo: { anim: ['mental', 'psiquico', 'espiral'] },
  'imagem-espelhada': { anim: ['ilusao', 'caos', 'duplicatas'] },
  'infligir-ferimentos': { anim: ['toque', 'trevas', 'garra'] },
  'infortunio-de-sszzaas': { anim: ['dreno', 'veneno', 'maldicao'], nota: '–2 na resistência mais baixa do alvo.' },
  'instante-estoico': { anim: ['escudo', 'metal', 'pele'] },
  'jato-corrosivo': { anim: ['raio', 'acido', 'jato'] },
  'leque-cromatico': { sucesso: 'parcial', falhou: ['atordoado:1', 'ofuscado'], passou: ['ofuscado'], anim: ['cone', 'caos', 'prisma'] },
  luz: { alvo: 'nenhum', res: undefined, sucesso: undefined, anim: ['campo', 'luz', 'luz'] },
  'maaais-klunc': { anim: ['transmutacao', 'natureza', 'musculos'] },
  'magia-dadivosa': { anim: ['aura', 'caos', 'dadiva'] },
  nevoa: { alvo: 'nenhum', anim: ['campo', 'ar', 'nevoa'] },
  'orbe-do-oceano': { anim: ['escudo', 'agua', 'bolha'] },
  orientacao: { anim: ['adivinhacao', 'ouro', 'orientacao'] },
  'ossos-de-adamante': { falhou: undefined, anim: ['transmutacao', 'metal', 'ossos'] },
  'paixao-de-marah': { anim: ['aura', 'psiquico', 'coracoes'] },
  'percepcao-rubra': { anim: ['aura', 'tormenta', 'olho'] },
  perdicao: { alvo: 'inimigos', anim: ['aura', 'trevas', 'maldicao'] },
  'perturbacao-sombria': { anim: ['campo', 'trevas', 'vultos'] },
  'poder-de-kallyadranoch': { persistente: 'rodadas', anim: ['aura', 'fogo', 'dragao'] },
  'posse-de-arsenal': { alvo: 'si', anim: ['arma', 'metal', 'vinculo'] },
  'primor-atletico': { anim: ['transmutacao', 'natureza', 'vigor'] },
  profanar: { alvo: 'nenhum', anim: ['campo', 'trevas', 'profanar'] },
  'protecao-de-tauron': { alvo: 'aliado', maxAlvos: 1, falhou: undefined, anim: ['escudo', 'ouro', 'touro'] },
  'protecao-divina': { anim: ['escudo', 'ouro', 'protecao'] },
  'punho-de-mitral': { anim: ['transmutacao', 'metal', 'punho'] },
  'queda-suave': { alvo: 'qualquer', anim: ['aura', 'ar', 'pena'] },
  'raio-do-enfraquecimento': { falhou: ['fatigado'], passou: ['vulneravel'], anim: ['raio', 'trevas', 'raio-purpura'] },
  'resistencia-a-energia': { anim: ['escudo', 'arcano', 'elementos'], nota: 'RD 10 contra o tipo escolhido.' },
  santuario: { alvo: 'aliado', res: undefined, sucesso: undefined, anim: ['escudo', 'ouro', 'santuario'], nota: 'Quem tentar ação hostil contra o alvo faz Vontade; se falhar, perde a ação.' },
  'seta-infalivel-de-talude': { alvo: 'inimigos', maxAlvos: 2, dano: '1d4+1', tipoDano: 'essencia', anim: ['projetil', 'arcano', 'seta', 2], nota: 'Duas setas: escolha 2 alvos ou repita o mesmo alvo.' },
  'sigilo-de-sszzaas': { anim: ['ilusao', 'veneno', 'sigilo'] },
  'siroco-de-azgher': { dano: '3d6', tipoDano: 'corte', anim: ['sopro', 'terra', 'areia'], nota: '3d6 sem armadura, 2d6 com armadura leve, 1d6 com pesada.' },
  sono: { falhou: ['inconsciente', 'caido'], passou: ['fatigado:2'], anim: ['mental', 'psiquico', 'sono'], nota: 'Em combate, em vez de dormir o alvo fica exausto por 1 rodada e depois fatigado.' },
  'sorriso-da-fortuna': { persistente: undefined, anim: ['aura', 'caos', 'sorte'] },
  'suporte-ambiental': { anim: ['escudo', 'agua', 'bolha'] },
  teia: { falhou: ['enredado'], anim: ['campo', 'natureza', 'teia'] },
  'toque-chocante': { anim: ['toque', 'eletricidade', 'arcos'] },
  'toque-de-megalokk': { anim: ['transmutacao', 'sangue', 'monstro'] },
  'toque-do-horizonte': { alvo: 'aliado', maxAlvos: 1, anim: ['arma', 'ar', 'mira'] },
  'tranca-arcana': { alvo: 'nenhum', anim: ['escudo', 'arcano', 'tranca'] },
  tranquilidade: { falhou: ['enfeiticado'], passou: [], anim: ['mental', 'agua', 'calma'], nota: 'Falhou: indiferente e não pode agir com hostilidade. Passou: –2 em ataques.' },
  'transmutar-objetos': { alvo: 'nenhum', anim: ['transmutacao', 'arcano', 'forja'] },
  'visao-mistica': { anim: ['adivinhacao', 'arcano', 'olhos-azuis'] },
  'vitalidade-fantasma': { temp: '2d10', anim: ['dreno', 'natureza', 'vitalidade'] },
  'voz-da-razao': { anim: ['aura', 'ouro', 'pergaminho'] },

  // ---------------- 2º circulo ----------------
  'aliado-animal': { alvo: 'nenhum', anim: ['convocacao', 'natureza', 'animal'] },
  'alterar-tamanho': { alvo: 'nenhum', anim: ['transmutacao', 'arcano', 'tamanho'] },
  'amarras-etereas': { falhou: ['agarrado'], anim: ['chao', 'arcano', 'correntes'] },
  'aparencia-perfeita': { anim: ['ilusao', 'ouro', 'brilho'] },
  augurio: { anim: ['adivinhacao', 'ouro', 'runas'] },
  'aura-de-morte': {
    alvo: 'inimigos', dano: '2d8', perda: true, persistente: 'cena', anim: ['onda', 'trevas', 'aura-morte'], nota: 'Você também perde 1d6 PV agora e no início de cada turno seu.',
    usos: [{ nome: 'Pulso (início do seu turno)', alvo: 'inimigos', dano: '2d8', perda: true, anim: ['onda', 'trevas', 'aura-morte'], nota: 'Você perde 1d6 PV.' }],
  },
  'bola-de-fogo': { anim: ['explosao', 'fogo', 'bola'] },
  'campo-de-forca': { temp: '30', anim: ['escudo', 'arcano', 'campo'] },
  'camuflagem-ilusoria': { anim: ['ilusao', 'agua', 'distorcao'] },
  'circulo-da-justica': { alvo: 'nenhum', res: undefined, sucesso: undefined, anim: ['campo', 'ouro', 'balanca'] },
  condicao: { alvo: 'aliados', maxAlvos: 5, anim: ['adivinhacao', 'ouro', 'pulso'] },
  'conjurar-armadilha': { alvo: 'nenhum', anim: ['chao', 'metal', 'armadilha'] },
  'conjurar-mortos-vivos': {
    alvo: 'nenhum', anim: ['convocacao', 'trevas', 'esqueletos'],
    usos: [{ nome: 'Esqueletos atacam (ação padrão)', alvo: 'inimigos', dano: '1d6+2', tipoDano: 'trevas', anim: ['toque', 'trevas', 'ossos'], nota: 'Cada esqueleto causa o dano em uma criatura adjacente.' }],
  },
  'controlar-fogo': { falhou: undefined, alvo: 'nenhum', dano: undefined, tipoDano: undefined, anim: ['transmutacao', 'fogo', 'chamas'], nota: 'Escolha: Chamejar (armas +1d6 fogo), Esquentar, Extinguir ou Modelar.' },
  'controlar-madeira': { alvo: 'nenhum', anim: ['transmutacao', 'natureza', 'madeira'] },
  'couraca-de-allihanna': { alvo: 'aliado', maxAlvos: 1, anim: ['escudo', 'natureza', 'casca'] },
  'cranio-voador-de-vladislav': { falhou: ['abalado'], anim: ['projetil', 'trevas', 'cranio'], nota: 'Inimigos a 3m do alvo também ficam abalados (já abalados: apavorados).' },
  'desafio-corajoso': { alvo: 'aliado', res: undefined, sucesso: undefined, anim: ['aura', 'ouro', 'desafio'] },
  'desespero-esmagador': { sucesso: 'parcial', falhou: ['fraco', 'frustrado'], passou: ['fraco:1', 'frustrado:1'], anim: ['cone', 'trevas', 'lagrimas'] },
  'desfazer-engenhoca': { falhou: undefined, alvo: 'qualquer', anim: ['escudo', 'metal', 'engrenagens'] },
  'dissipar-magia': { alvo: 'qualquer', anim: ['onda', 'arcano', 'dissipar'], nota: 'Faça Misticismo: dissipa magias com CD igual ou menor.' },
  'emular-magia': { anim: ['aura', 'arcano', 'eco'] },
  'enxame-de-pestes': {
    alvo: 'inimigo', maxAlvos: 1, anim: ['convocacao', 'natureza', 'enxame'],
    usos: [{ nome: 'Enxame morde (fim do seu turno)', alvo: 'inimigos', dano: '2d12', tipoDano: 'corte', res: 'fort', sucesso: 'metade', anim: ['convocacao', 'natureza', 'enxame'] }],
  },
  'esculpir-sons': { anim: ['ilusao', 'som', 'notas'] },
  'fisico-divino': { anim: ['transmutacao', 'ouro', 'vigor'] },
  'flecha-acida': { anim: ['projetil', 'acido', 'flecha'], nota: 'Se falhou: mais 2d6 de ácido no início dos dois próximos turnos do alvo.' },
  'globo-da-verdade-de-gwen': { alvo: 'nenhum', anim: ['adivinhacao', 'ouro', 'globo'] },
  invisibilidade: { falhou: undefined, anim: ['ilusao', 'ar', 'sumir'] },
  'invocar-fagulha-elemental': { alvo: 'nenhum', anim: ['convocacao', 'fogo', 'elemental'] },
  'ligacao-telepatica': { alvo: 'aliados', maxAlvos: 2, anim: ['mental', 'psiquico', 'elo'] },
  localizacao: { alvo: 'si', anim: ['adivinhacao', 'ouro', 'bussola'] },
  mapear: { alvo: 'nenhum', anim: ['adivinhacao', 'fogo', 'mapa'] },
  'maquina-de-combate': { anim: ['transmutacao', 'eletricidade', 'engrenagens'] },
  'marca-da-obediencia': { falhou: ['enfeiticado'], anim: ['toque', 'psiquico', 'marca'], nota: 'O alvo segue a ordem; a cada rodada pode tentar Vontade para se livrar.' },
  'mente-divina': { anim: ['aura', 'ouro', 'mente'] },
  metamorfose: { anim: ['transmutacao', 'caos', 'forma'] },
  'miasma-mefitico': { sucesso: 'metade', falhou: ['enjoado:1'], anim: ['explosao', 'veneno', 'nuvem'] },
  'momento-de-tormenta': {
    alvo: 'nenhum', dano: undefined, tipoDano: undefined, res: undefined, sucesso: undefined, anim: ['campo', 'tormenta', 'nuvem-rubra'],
    nota: 'A nuvem fica: uma vez por turno, ação de movimento para um fenômeno.',
    usos: [
      { nome: 'Chuva ácida', alvo: 'inimigos', dano: '6d4', tipoDano: 'acido', anim: ['queda', 'acido', 'chuva'] },
      { nome: 'Neblina venenosa', alvo: 'inimigos', dano: '2d12', perda: true, res: 'fort', sucesso: 'anula', anim: ['campo', 'veneno', 'neblina'] },
      { nome: 'Raios escarlates', alvo: 'inimigos', maxAlvos: 6, dano: '6d8', tipoDano: 'eletricidade', res: 'ref', sucesso: 'metade', anim: ['queda', 'tormenta', 'raios'] },
      { nome: 'Pesadelos reais', alvo: 'inimigos', dano: '4d6', tipoDano: 'psiquico', res: 'von', sucesso: 'metade', anim: ['mental', 'tormenta', 'pesadelo'], nota: 'Quem falhar também perde 1d4 PM.' },
    ],
  },
  'montaria-arcana': { alvo: 'nenhum', anim: ['convocacao', 'trevas', 'cavalo'] },
  oracao: { alvo: 'aliados', anim: ['aura', 'ouro', 'oracao'], nota: 'Aliados +2 em perícias e dano; inimigos no alcance –2.' },
  piscar: { anim: ['teleporte', 'arcano', 'piscar'] },
  'pocao-explosiva': { alvo: 'nenhum', anim: ['transmutacao', 'fogo', 'pocao'] },
  'punicao-do-profano': { anim: ['palavra', 'ouro', 'brado'], nota: 'Só afeta devotos de deuses de energia oposta à sua.' },
  purificacao: { falhou: undefined, alvo: 'aliado', remove: ['abalado', 'apavorado', 'alquebrado', 'atordoado', 'cego', 'confuso', 'debilitado', 'enjoado', 'envenenado', 'esmorecido', 'exausto', 'fascinado', 'fatigado', 'fraco', 'frustrado', 'lento', 'ofuscado', 'paralisado', 'pasmo', 'surdo'], anim: ['cura', 'agua', 'purificar'], nota: 'Remove uma condição (com +2 PM, todas).' },
  'raio-solar': { res: 'ref', sucesso: 'metade', falhou: ['ofuscado:1'], anim: ['raio', 'luz', 'raio-solar'], nota: 'Mortos-vivos sofrem 4d12 em vez de 4d8.' },
  refugio: { falhou: undefined, alvo: 'nenhum', anim: ['escudo', 'arcano', 'domo'] },
  relampago: { anim: ['raio', 'eletricidade', 'relampago'] },
  'rogar-maldicao': { falhou: ['esmorecido'], anim: ['dreno', 'trevas', 'maldicao'], nota: 'Escolha a maldição: Debilidade (esmorecido, sem falar nem lançar magias), Doença, Fraqueza, Isolamento…' },
  'runa-de-protecao': { alvo: 'nenhum', dano: undefined, tipoDano: undefined, anim: ['campo', 'arcano', 'runa'], nota: 'A runa explode (6d6) quando alguém entra na área.' },
  'salto-dimensional': { anim: ['teleporte', 'arcano', 'salto'] },
  'servos-invisiveis': { alvo: 'nenhum', anim: ['convocacao', 'ar', 'servos'] },
  silencio: { alvo: 'inimigos', falhou: ['surdo'], anim: ['campo', 'som', 'silencio'] },
  'soco-de-arsenal': { somaAtributo: 'for', falhou: ['caido'], anim: ['projetil', 'metal', 'punho'], nota: 'Quem falhar é empurrado 3m para longe de você.' },
  'sopro-das-uivantes': { dano2: undefined, falhou: ['caido'], anim: ['sopro', 'frio', 'vento-gelido'], nota: 'Médios ou menores que falham são empurrados 6m; batendo numa parede, +2d6 de impacto.' },
  'sussurros-insanos': { falhou: ['confuso'], anim: ['mental', 'psiquico', 'sussurros'] },
  'tempestade-divina': {
    alvo: 'nenhum', anim: ['campo', 'ar', 'tempestade'],
    usos: [{ nome: 'Raio da tempestade (aprimoramento)', alvo: 'inimigo', maxAlvos: 1, dano: '3d8', tipoDano: 'eletricidade', res: 'ref', sucesso: 'metade', anim: ['queda', 'eletricidade', 'raio-celeste'], nota: 'Só se você pagou o aprimoramento de +1 PM.' }],
  },
  'toque-vampirico': { drenar: true, anim: ['dreno', 'trevas', 'vampiro'] },
  'traicao-da-lamina': { alvo: 'inimigo', anim: ['arma', 'veneno', 'serpente'], nota: 'Quando o portador atacar, faz Vontade; se falhar, o golpe volta contra ele.' },
  'traicao-magica': { dano: '1d8', tipoDano: 'essencia', anim: ['onda', 'arcano', 'descarga'], nota: '1d8 por círculo de magias ativas no alvo (5d8 se estiver com Velocidade e Voo). Ajuste o dano no registro.' },
  transposicao: { alvo: 'aliados', maxAlvos: 2, anim: ['teleporte', 'arcano', 'troca'] },
  velocidade: { anim: ['tempo', 'ar', 'velocidade'] },
  'vestimenta-da-fe': { alvo: 'aliado', maxAlvos: 1, anim: ['escudo', 'ouro', 'vestes'] },
  'viagem-onirica': { anim: ['teleporte', 'espirito', 'sonho'] },
  'voz-divina': { alvo: 'si', anim: ['adivinhacao', 'ouro', 'voz'] },

  // ---------------- 3º circulo ----------------
  'ancora-dimensional': { alvo: 'inimigo', anim: ['chao', 'natureza', 'ancora'] },
  'anular-a-luz': { alvo: 'inimigos', falhou: ['enjoado:2'], anim: ['onda', 'trevas', 'anular-luz'], nota: 'Aliados na área ganham +4 na Defesa; magias de até 3º círculo podem ser dissipadas (Religião).' },
  banimento: { falhou: [], passou: ['enjoado:2'], anim: ['palavra', 'ouro', 'banir'], nota: 'Falhou: espíritos voltam ao plano de origem; mortos-vivos vão a 0 PV.' },
  'coluna-de-chamas': { dano: '6d6', tipoDano: 'fogo', dano2: '6d6', tipoDano2: 'luz', anim: ['queda', 'fogo', 'pilar'] },
  'comunhao-com-a-natureza': { anim: ['adivinhacao', 'natureza', 'raizes'] },
  'contato-extraplanar': { anim: ['adivinhacao', 'trevas', 'portal'] },
  'controlar-agua': { falhou: undefined, alvo: 'nenhum', dano: undefined, tipoDano: undefined, res: undefined, sucesso: undefined, anim: ['transmutacao', 'agua', 'ondas'], nota: 'Escolha: Congelar, Derreter, Enchente, Evaporar (10d8 de fogo em criaturas de água) ou Partir.' },
  'controlar-terra': { alvo: 'inimigos', dano: '10d6', tipoDano: 'impacto', res: 'ref', sucesso: 'metade', anim: ['chao', 'terra', 'desabamento'], nota: 'Dano só no efeito Amolecer sob teto/coluna (desabamento). Outros efeitos: Modelar, Solidificar.' },
  'convocacao-instantanea': { alvo: 'si', anim: ['teleporte', 'arcano', 'objeto'] },
  'coracao-imortal': { anim: ['aura', 'sangue', 'coracao'] },
  'despertar-consciencia': { alvo: 'nenhum', anim: ['convocacao', 'natureza', 'despertar'] },
  'dificultar-deteccao': { anim: ['ilusao', 'trevas', 'oculto'] },
  'dispersar-as-trevas': { alvo: 'inimigos', falhou: ['cego:2'], anim: ['onda', 'luz', 'aurora'], nota: 'Aliados na área: +4 em resistências e redução de trevas 10 até o fim da cena.' },
  'enxame-rubro-de-ichabod': {
    alvo: 'inimigos', anim: ['convocacao', 'tormenta', 'enxame'],
    usos: [{ nome: 'Enxame devora (fim do seu turno)', alvo: 'inimigos', dano: '4d12', tipoDano: 'acido', res: 'ref', sucesso: 'metade', anim: ['convocacao', 'tormenta', 'enxame'] }],
  },
  'erupcao-glacial': { dano: '4d6', tipoDano: 'frio', dano2: '4d6', tipoDano2: 'corte', dano2SoFalha: true, sucesso: 'parcial', falhou: ['caido'], anim: ['chao', 'frio', 'estacas'] },
  'ferver-sangue': {
    dano: '4d8', tipoDano: 'fogo', falhou: ['enjoado:1'], anim: ['dreno', 'fogo', 'sangue-fervendo'], nota: 'Dois testes de Fortitude seguidos dissipam a magia. Se chegar a 0 PV, explode (6d6 de fogo em volta).',
    usos: [{ nome: 'Sangue ferve (início do turno do alvo)', alvo: 'inimigo', maxAlvos: 1, dano: '4d8', tipoDano: 'fogo', res: 'fort', sucesso: 'metade', falhou: ['enjoado:1'], anim: ['dreno', 'fogo', 'sangue-fervendo'] }],
  },
  'globo-de-invulnerabilidade': { falhou: undefined, anim: ['escudo', 'arcano', 'globo'] },
  heroismo: { temp: '40', anim: ['aura', 'ouro', 'heroismo'], nota: 'Imune a medo e +4 em ataque e dano contra o inimigo de maior ND.' },
  'ilusao-lacerante': {
    alvo: 'inimigos', anim: ['ilusao', 'sangue', 'laminas'], nota: 'Dano não letal.',
    usos: [{ nome: 'Ilusão fere (início do turno de cada vítima)', alvo: 'inimigos', dano: '3d6', tipoDano: 'psiquico', res: 'von', sucesso: 'anula', anim: ['ilusao', 'sangue', 'laminas'] }],
  },
  imobilizar: { falhou: ['paralisado'], passou: ['lento'], anim: ['mental', 'psiquico', 'correntes'], nota: 'Ação completa: novo teste de Vontade para se libertar.' },
  'lanca-ignea-de-aleph': { dano: '4d6', tipoDano: 'fogo', dano2: '4d6', tipoDano2: 'perfuracao', falhou: ['em-chamas'], anim: ['projetil', 'fogo', 'lanca'], nota: 'Em chamas desta magia causam 2d6 por rodada.' },
  'lendas-e-historias': { alvo: 'qualquer', anim: ['adivinhacao', 'ouro', 'livro'] },
  'manto-de-sombras': { falhou: undefined, anim: ['aura', 'trevas', 'manto'] },
  miragem: { alvo: 'nenhum', res: undefined, sucesso: undefined, anim: ['ilusao', 'caos', 'miragem'] },
  'missao-divina': { anim: ['palavra', 'ouro', 'missao'] },
  'muralha-elemental': { alvo: 'nenhum', dano: undefined, tipoDano: undefined, res: undefined, sucesso: undefined, anim: ['chao', 'fogo', 'muralha'], nota: 'Atravessar a muralha (ou começar o turno nela) causa 6d6 do elemento.',
    usos: [{ nome: 'Alguém atravessa a muralha', alvo: 'inimigos', dano: '6d6', tipoDano: 'fogo', anim: ['chao', 'fogo', 'muralha'] }] },
  'pele-de-pedra': { anim: ['transmutacao', 'terra', 'pedra'] },
  'poeira-da-podridao': {
    alvo: 'inimigos', res: 'fort', sucesso: 'metade', anim: ['campo', 'trevas', 'poeira'], nota: 'Quem falhar não recupera PV por 1 rodada.',
    usos: [{ nome: 'Podridão (início do seu turno)', alvo: 'inimigos', dano: '2d8+8', tipoDano: 'trevas', res: 'fort', sucesso: 'metade', anim: ['campo', 'trevas', 'poeira'] }],
  },
  'potencia-divina': { anim: ['transmutacao', 'ouro', 'gigante'] },
  'protecao-contra-magia': { anim: ['escudo', 'arcano', 'runas'] },
  'selo-de-mana': { anim: ['toque', 'arcano', 'selo'], nota: 'Toda vez que o alvo gastar PM, faz Vontade; se falhar, a ação não funciona.' },
  'servo-divino': { alvo: 'nenhum', anim: ['convocacao', 'ouro', 'anjo'] },
  'servo-morto-vivo': { alvo: 'nenhum', anim: ['convocacao', 'trevas', 'zumbi'] },
  'sopro-da-salvacao': { falhou: undefined, alvo: 'aliados', remove: ['abalado', 'atordoado', 'apavorado', 'alquebrado', 'cego', 'confuso', 'debilitado', 'enfeiticado', 'enjoado', 'esmorecido', 'exausto', 'fascinado', 'fatigado', 'fraco', 'frustrado', 'lento', 'paralisado', 'pasmo', 'surdo'], anim: ['cone', 'luz', 'poeira-reluzente'], nota: 'Remove uma condição de cada aliado (com +4 PM, todas).' },
  telecinesia: { alvo: 'qualquer', anim: ['transmutacao', 'psiquico', 'levitar'] },
  teletransporte: { falhou: undefined, alvo: 'aliados', maxAlvos: 5, anim: ['teleporte', 'arcano', 'portal'], nota: 'Teste de Misticismo (CD 20 a 40) conforme o destino.' },
  'tentaculos-de-trevas': {
    alvo: 'inimigos', dano: undefined, tipoDano: undefined, anim: ['chao', 'trevas', 'tentaculos'], nota: 'Faça agarrar (Misticismo) contra cada criatura na área; quem já estava agarrado é esmagado.',
    usos: [{ nome: 'Tentáculos esmagam (agarrados)', alvo: 'inimigos', dano: '4d6', tipoDano: 'trevas', anim: ['chao', 'trevas', 'tentaculos'] }],
  },
  'transformacao-de-guerra': { temp: '30', anim: ['transmutacao', 'metal', 'guerra'], nota: '+6 na Defesa, ataque e dano corpo a corpo; não lança magias.' },
  'viagem-arborea': { anim: ['teleporte', 'natureza', 'arvore'] },
  videncia: { alvo: 'qualquer', anim: ['adivinhacao', 'agua', 'espelho'] },
  voo: { anim: ['transmutacao', 'ar', 'asas'] },

  // ---------------- 4º circulo ----------------
  'alterar-memoria': { anim: ['mental', 'psiquico', 'memoria'] },
  'animar-objetos': { alvo: 'nenhum', anim: ['convocacao', 'arcano', 'objetos'] },
  'assassino-fantasmagorico': { falhou: undefined, dano: undefined, tipoDano: undefined, sucesso: 'anula', anim: ['ilusao', 'trevas', 'espectro'], nota: 'Se falhar em Vontade, faz Fortitude: falhou, cai a –1 PV (morrendo); passou, sofre 6d6 de trevas.' },
  'campo-antimagia': { anim: ['escudo', 'arcano', 'antimagia'] },
  'circulo-da-restauracao': {
    alvo: 'nenhum', anim: ['campo', 'luz', 'circulo-cura'], nota: 'Quem terminar o turno no círculo recupera 3d8+3 PV e 1 PM.',
    usos: [{ nome: 'Círculo cura (fim do turno)', alvo: 'aliados', cura: '3d8+3', anim: ['cura', 'luz', 'circulo-cura'] }],
  },
  'colera-de-azgher': { falhou: ['cego:2', 'em-chamas'], anim: ['explosao', 'luz', 'sol'], nota: 'Mortos-vivos sofrem 10d8.' },
  'conceder-milagre': { anim: ['aura', 'ouro', 'milagre'] },
  'conjurar-elemental': { alvo: 'nenhum', anim: ['convocacao', 'fogo', 'elemental-grande'] },
  'controlar-a-gravidade': { falhou: undefined, alvo: 'inimigos', anim: ['campo', 'arcano', 'gravidade'], nota: 'Escolha: Aumentar (Atletismo ou fatigado/caído), Inverter ou Reduzir.' },
  'controlar-o-clima': { alvo: 'nenhum', anim: ['campo', 'ar', 'clima'] },
  'cupula-de-repulsao': { res: undefined, sucesso: undefined, anim: ['escudo', 'ouro', 'cupula'] },
  desintegrar: { dano: '10d12', danoPassou: '2d12', sucesso: 'parcial', anim: ['raio', 'acido', 'desintegrar'], nota: 'Se chegar a 0 PV, vira pó.' },
  'duplicata-ilusoria': { alvo: 'nenhum', anim: ['ilusao', 'caos', 'duplicata'] },
  'explosao-caleidoscopica': { alvo: 'inimigos', falhou: ['atordoado:2', 'enjoado'], passou: ['atordoado:1', 'enjoado:2'], anim: ['explosao', 'caos', 'caleidoscopio'], nota: 'ND 4 ou menor que falha fica inconsciente; ND 10+ sofre bem menos (veja a magia).' },
  'forma-eterea': { anim: ['ilusao', 'espirito', 'etereo'] },
  'guardiao-divino': { falhou: undefined,
    alvo: 'nenhum', anim: ['convocacao', 'luz', 'orbe'], nota: '100 pontos de luz: 1 PV por ponto, ou 3 pontos por condição.',
    usos: [{ nome: 'Guardião cura', alvo: 'aliado', maxAlvos: 1, cura: '10', anim: ['cura', 'luz', 'orbe'], nota: 'Ajuste a cura gasta dos pontos de luz.' }],
  },
  libertacao: { anim: ['escudo', 'ar', 'liberdade'] },
  'ligacao-sombria': { anim: ['dreno', 'trevas', 'elo'] },
  'manto-do-cruzado': { dano: undefined, tipoDano: undefined, cura: undefined,
    anim: ['aura', 'ouro', 'manto'], nota: 'Escolha luz ou trevas ao aprender a magia.',
    usos: [
      { nome: 'Manto de Luz: cura (início do turno)', alvo: 'aliados', cura: '2d8', anim: ['cura', 'luz', 'manto'] },
      { nome: 'Manto de Trevas: dano (início do turno)', alvo: 'inimigos', dano: '4d8', tipoDano: 'trevas', drenar: true, anim: ['onda', 'trevas', 'manto'] },
    ],
  },
  'mao-poderosa-de-talude': {
    alvo: 'nenhum', dano: undefined, tipoDano: undefined, anim: ['convocacao', 'arcano', 'mao-gigante'],
    usos: [{ nome: 'Mão esmaga', alvo: 'inimigo', maxAlvos: 1, dano: '2d6+10', tipoDano: 'impacto', anim: ['queda', 'arcano', 'mao-gigante'], nota: 'A mão faz a manobra agarrar com Misticismo +10.' }],
  },
  marionete: { falhou: [], anim: ['mental', 'psiquico', 'fios'], nota: 'A cada turno do alvo, novo teste de Fortitude.' },
  'muralha-de-ossos': { alvo: 'inimigos', res: 'ref', sucesso: 'parcial', falhou: ['agarrado'], dano: '4d8', tipoDano: 'corte', anim: ['chao', 'trevas', 'ossos'] },
  premonicao: { anim: ['adivinhacao', 'tempo', 'visao'] },
  'raio-polar': { falhou: ['paralisado'], passou: ['lento:1'], anim: ['raio', 'frio', 'raio-polar'], nota: 'Preso no gelo: bloco com 20 PV, RD 10, vulnerável a fogo.' },
  'relampago-flamejante-de-reynard': { falhou: undefined,
    alvo: 'nenhum', dano: undefined, tipoDano: undefined, res: undefined, sucesso: undefined, anim: ['aura', 'fogo', 'maos-elementais'],
    usos: [
      { nome: 'Bola de fogo (movimento)', alvo: 'inimigos', dano: '10d6', tipoDano: 'fogo', res: 'ref', sucesso: 'metade', anim: ['explosao', 'fogo', 'bola'] },
      { nome: 'Relâmpago (movimento)', alvo: 'inimigos', dano: '10d6', tipoDano: 'eletricidade', res: 'ref', sucesso: 'metade', anim: ['raio', 'eletricidade', 'relampago'] },
      { nome: 'Rajada mista (padrão, encerra)', alvo: 'inimigos', dano: '10d12', tipoDano: 'fogo', dano2: '10d12', tipoDano2: 'eletricidade', res: 'ref', sucesso: 'metade', encerra: true, anim: ['explosao', 'eletricidade', 'rajada-mista'] },
    ],
  },
  sonho: { alvo: 'qualquer', anim: ['mental', 'espirito', 'sonho'] },
  'talho-invisivel-de-edauros': { falhou: ['sangrando'], anim: ['cone', 'ar', 'lamina-de-ar'] },
  terremoto: { alvo: 'inimigos', dano: '12d6', tipoDano: 'impacto', res: 'ref', sucesso: 'metade', falhou: ['atordoado:1'], anim: ['chao', 'terra', 'terremoto'], nota: 'O efeito depende do terreno (caverna, construção ou espaço aberto).' },
  'transformacao-em-dragao': {
    dano: undefined, tipoDano: undefined, anim: ['transmutacao', 'fogo', 'dragao'], nota: '+2 em For, Con, Int e Car, +5 na Defesa e redução 30 ao elemento.',
    usos: [{ nome: 'Sopro dracônico (ação padrão)', alvo: 'inimigos', dano: '8d6+8', tipoDano: 'fogo', res: 'ref', sucesso: 'metade', anim: ['sopro', 'fogo', 'sopro-dragao'] }],
  },
  'viagem-planar': { anim: ['teleporte', 'espirito', 'portal'] },
  'visao-da-verdade': { anim: ['adivinhacao', 'luz', 'olho'] },

  // ---------------- 5º circulo ----------------
  'alterar-destino': { anim: ['adivinhacao', 'tempo', 'fios-destino'] },
  aprisionamento: { falhou: [], nota: 'Falhou: o alvo é aprisionado (escolha a prisão). Passou: imune por uma semana.', anim: ['escudo', 'arcano', 'prisao'] },
  'aura-divina': { alvo: 'inimigos', falhou: [], anim: ['onda', 'ouro', 'aura-divina'], nota: 'Você e aliados ganham +5 ou +10 na Defesa e resistências; inimigos que falham recebem uma condição a sua escolha.' },
  'barragem-elemental-de-vectorius': { falhou: undefined, dano: '6d6', tipoDano: 'acido', dano2: '6d6', tipoDano2: 'eletricidade', anim: ['explosao', 'caos', 'esferas', 4], nota: 'Quatro esferas (ácido, eletricidade, fogo, frio): ajuste quem recebeu cada uma.' },
  'buraco-negro': { alvo: 'inimigos', falhou: ['caido'], anim: ['campo', 'trevas', 'buraco-negro'], nota: 'Três turnos: quem falha é puxado 30m; quem termina no buraco desaparece.' },
  'chuva-de-meteoros': { dano: '15d6', tipoDano: 'impacto', dano2: '15d6', tipoDano2: 'fogo', falhou: ['caido', 'agarrado'], anim: ['queda', 'fogo', 'meteoros'] },
  'controlar-o-tempo': { anim: ['tempo', 'tempo', 'relogio'] },
  'deflagracao-de-mana': { alvo: 'inimigos', dano: '150', tipoDano: 'essencia', res: 'fort', sucesso: 'metade', anim: ['explosao', 'arcano', 'estrela'], nota: 'Itens mágicos na área ficam mundanos.' },
  desejo: { alvo: 'nenhum', res: undefined, sucesso: undefined, anim: ['transmutacao', 'ouro', 'desejo'] },
  'engenho-de-mana': { alvo: 'nenhum', anim: ['escudo', 'arcano', 'engenho'] },
  'furia-do-panteao': { falhou: undefined,
    alvo: 'nenhum', dano: undefined, tipoDano: undefined, res: undefined, sucesso: undefined, anim: ['campo', 'ar', 'tempestade-divina'],
    usos: [
      { nome: 'Nevasca', alvo: 'inimigos', dano: '10d6', tipoDano: 'frio', res: 'fort', sucesso: 'metade', anim: ['queda', 'frio', 'nevasca'] },
      { nome: 'Raios', alvo: 'inimigos', maxAlvos: 6, dano: '10d8', tipoDano: 'eletricidade', res: 'ref', sucesso: 'metade', anim: ['queda', 'eletricidade', 'raios'] },
      { nome: 'Siroco', alvo: 'inimigos', dano: '5d6', tipoDano: 'corte', dano2: '5d6', tipoDano2: 'fogo', res: 'fort', sucesso: 'metade', falhou: ['sangrando'], anim: ['sopro', 'terra', 'areia'] },
      { nome: 'Trovões', alvo: 'inimigos', dano: '10d6', tipoDano: 'impacto', res: 'fort', sucesso: 'metade', falhou: ['desprevenido:1'], anim: ['onda', 'som', 'trovao'] },
    ],
  },
  'intervencao-divina': { alvo: 'aliados', maxAlvos: 10, res: undefined, sucesso: undefined, cura: '999', anim: ['cura', 'ouro', 'intervencao'], nota: 'Cura todos os PV e condições de até 10 criaturas, ou outro milagre.' },
  invulnerabilidade: { falhou: undefined, anim: ['escudo', 'ouro', 'invulneravel'] },
  'katana-celestial': { falhou: ['cego', 'surdo'], anim: ['raio', 'luz', 'katana'], nota: 'Mortos-vivos sofrem 12d12.' },
  'lagrimas-de-wynna': { anim: ['dreno', 'arcano', 'lagrimas'], nota: 'Falhou: sem magias arcanas na cena. Passou: por 1 rodada.' },
  legiao: { alvo: 'inimigos', maxAlvos: 10, falhou: ['enfeiticado'], passou: ['abalado:1'], anim: ['mental', 'psiquico', 'coroa'] },
  'mata-dragao': { falhou: undefined, anim: ['cone', 'arcano', 'mata-dragao'], nota: 'Cada 12 nos dados de dano soma +1d12.' },
  'palavra-primordial': { sucesso: 'parcial', dano: undefined, tipoDano: undefined, falhou: ['atordoado:3'], passou: ['desprevenido:2'], anim: ['palavra', 'ouro', 'primordial'], nota: 'Escolha Atordoar, Cegar ou Matar (10d8 se passar).' },
  possessao: { falhou: [], anim: ['mental', 'espirito', 'possessao'] },
  'projetar-consciencia': { anim: ['teleporte', 'espirito', 'projecao'] },
  'reanimacao-impura': { alvo: 'qualquer', anim: ['convocacao', 'trevas', 'reanimar'] },
  requiem: { alvo: 'inimigos', anim: ['ilusao', 'tempo', 'requiem'], nota: 'No início de cada turno, quem falhar em Vontade repete as ações do turno anterior (–5 cumulativo).' },
  'roubar-a-alma': { falhou: ['inconsciente', 'caido'], passou: ['abalado:1'], anim: ['dreno', 'espirito', 'alma'] },
  'segunda-chance': { alvo: 'aliado', maxAlvos: 1, falhou: undefined, cura: '200', remove: ['abalado', 'apavorado', 'alquebrado', 'atordoado', 'cego', 'confuso', 'debilitado', 'enjoado', 'envenenado', 'esmorecido', 'exausto', 'fascinado', 'fatigado', 'fraco', 'frustrado', 'lento', 'ofuscado', 'paralisado', 'pasmo', 'surdo'], anim: ['cura', 'fogo', 'fenix'] },
  semiplano: { alvo: 'nenhum', anim: ['teleporte', 'arcano', 'semiplano'] },
  'sombra-assassina': { anim: ['ilusao', 'trevas', 'sombra'], nota: 'A sombra repete contra o alvo toda ação hostil que ele fizer.' },
  'toque-da-morte': { res: 'fort', sucesso: 'parcial', anim: ['toque', 'trevas', 'morte'], nota: 'Só pede Fortitude se o alvo tiver menos da metade dos PV; se falhar, vai a –10 PV.' },
};
